-- Migration: Create role_permissions table
CREATE TABLE IF NOT EXISTS role_permissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  role VARCHAR(50) NOT NULL,
  category VARCHAR(100) NOT NULL,
  feature VARCHAR(150) NOT NULL,
  allowed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_role_feature (role, feature)
);

-- Seed default permissions
INSERT INTO role_permissions (role, category, feature, allowed) VALUES
-- Dashboard & Monitoring
('admin',      'Dashboard & Monitoring', 'Lihat Dashboard',          TRUE),
('admin',      'Dashboard & Monitoring', 'Pemantauan Langsung (Map)',TRUE),
('admin',      'Dashboard & Monitoring', 'Cuaca Laut',               TRUE),
('admin',      'Dashboard & Monitoring', 'Sinyal Darurat (SOS)',     TRUE),
('admin',      'Dashboard & Monitoring', 'Resolve SOS',              TRUE),
('operator',   'Dashboard & Monitoring', 'Lihat Dashboard',          TRUE),
('operator',   'Dashboard & Monitoring', 'Pemantauan Langsung (Map)',TRUE),
('operator',   'Dashboard & Monitoring', 'Cuaca Laut',               TRUE),
('operator',   'Dashboard & Monitoring', 'Sinyal Darurat (SOS)',     TRUE),
('operator',   'Dashboard & Monitoring', 'Resolve SOS',              TRUE),
('supervisor', 'Dashboard & Monitoring', 'Lihat Dashboard',          TRUE),
('supervisor', 'Dashboard & Monitoring', 'Pemantauan Langsung (Map)',TRUE),
('supervisor', 'Dashboard & Monitoring', 'Cuaca Laut',               TRUE),
('supervisor', 'Dashboard & Monitoring', 'Sinyal Darurat (SOS)',     TRUE),
('supervisor', 'Dashboard & Monitoring', 'Resolve SOS',              FALSE),
-- Perizinan & Trip
('admin',      'Perizinan & Trip', 'Lihat Data Trip',          TRUE),
('admin',      'Perizinan & Trip', 'Setujui / Tolak Trip',     TRUE),
('admin',      'Perizinan & Trip', 'Bulk Approve Trip',        TRUE),
('admin',      'Perizinan & Trip', 'Hapus Trip',               TRUE),
('admin',      'Perizinan & Trip', 'Export PDF / Logbook KKP', TRUE),
('operator',   'Perizinan & Trip', 'Lihat Data Trip',          TRUE),
('operator',   'Perizinan & Trip', 'Setujui / Tolak Trip',     TRUE),
('operator',   'Perizinan & Trip', 'Bulk Approve Trip',        TRUE),
('operator',   'Perizinan & Trip', 'Hapus Trip',               FALSE),
('operator',   'Perizinan & Trip', 'Export PDF / Logbook KKP', TRUE),
('supervisor', 'Perizinan & Trip', 'Lihat Data Trip',          TRUE),
('supervisor', 'Perizinan & Trip', 'Setujui / Tolak Trip',     FALSE),
('supervisor', 'Perizinan & Trip', 'Bulk Approve Trip',        FALSE),
('supervisor', 'Perizinan & Trip', 'Hapus Trip',               FALSE),
('supervisor', 'Perizinan & Trip', 'Export PDF / Logbook KKP', TRUE),
-- Hasil Tangkap
('admin',      'Hasil Tangkap', 'Lihat Data Tangkapan',    TRUE),
('admin',      'Hasil Tangkap', 'Tambah / Edit Tangkapan', TRUE),
('admin',      'Hasil Tangkap', 'Hapus Tangkapan',         TRUE),
('operator',   'Hasil Tangkap', 'Lihat Data Tangkapan',    TRUE),
('operator',   'Hasil Tangkap', 'Tambah / Edit Tangkapan', TRUE),
('operator',   'Hasil Tangkap', 'Hapus Tangkapan',         FALSE),
('supervisor', 'Hasil Tangkap', 'Lihat Data Tangkapan',    TRUE),
('supervisor', 'Hasil Tangkap', 'Tambah / Edit Tangkapan', FALSE),
('supervisor', 'Hasil Tangkap', 'Hapus Tangkapan',         FALSE),
-- Data Master
('admin',      'Data Master', 'Lihat Data Kapal',        TRUE),
('admin',      'Data Master', 'Tambah / Edit Kapal',     TRUE),
('admin',      'Data Master', 'Hapus Kapal',             TRUE),
('admin',      'Data Master', 'Lihat Data Perangkat',    TRUE),
('admin',      'Data Master', 'Tambah / Edit Perangkat', TRUE),
('admin',      'Data Master', 'Hapus Perangkat',         TRUE),
('admin',      'Data Master', 'Edit Zonasi Pelabuhan',   TRUE),
('admin',      'Data Master', 'Hapus Zonasi Pelabuhan',  TRUE),
('admin',      'Data Master', 'Edit Zonasi Tangkap',     TRUE),
('admin',      'Data Master', 'Hapus Zonasi Tangkap',    TRUE),
('operator',   'Data Master', 'Lihat Data Kapal',        TRUE),
('operator',   'Data Master', 'Tambah / Edit Kapal',     TRUE),
('operator',   'Data Master', 'Hapus Kapal',             FALSE),
('operator',   'Data Master', 'Lihat Data Perangkat',    TRUE),
('operator',   'Data Master', 'Tambah / Edit Perangkat', TRUE),
('operator',   'Data Master', 'Hapus Perangkat',         FALSE),
('operator',   'Data Master', 'Edit Zonasi Pelabuhan',   TRUE),
('operator',   'Data Master', 'Hapus Zonasi Pelabuhan',  FALSE),
('operator',   'Data Master', 'Edit Zonasi Tangkap',     TRUE),
('operator',   'Data Master', 'Hapus Zonasi Tangkap',    FALSE),
('supervisor', 'Data Master', 'Lihat Data Kapal',        TRUE),
('supervisor', 'Data Master', 'Tambah / Edit Kapal',     FALSE),
('supervisor', 'Data Master', 'Hapus Kapal',             FALSE),
('supervisor', 'Data Master', 'Lihat Data Perangkat',    TRUE),
('supervisor', 'Data Master', 'Tambah / Edit Perangkat', FALSE),
('supervisor', 'Data Master', 'Hapus Perangkat',         FALSE),
('supervisor', 'Data Master', 'Edit Zonasi Pelabuhan',   FALSE),
('supervisor', 'Data Master', 'Hapus Zonasi Pelabuhan',  FALSE),
('supervisor', 'Data Master', 'Edit Zonasi Tangkap',     FALSE),
('supervisor', 'Data Master', 'Hapus Zonasi Tangkap',    FALSE),
-- Manajemen Pengguna
('admin',      'Manajemen Pengguna', 'Lihat Daftar User',       TRUE),
('admin',      'Manajemen Pengguna', 'Tambah Akun',             TRUE),
('admin',      'Manajemen Pengguna', 'Edit Akun',               TRUE),
('admin',      'Manajemen Pengguna', 'Hapus Akun',              TRUE),
('admin',      'Manajemen Pengguna', 'Verifikasi Dokumen User', TRUE),
('operator',   'Manajemen Pengguna', 'Lihat Daftar User',       TRUE),
('operator',   'Manajemen Pengguna', 'Tambah Akun',             FALSE),
('operator',   'Manajemen Pengguna', 'Edit Akun',               TRUE),
('operator',   'Manajemen Pengguna', 'Hapus Akun',              FALSE),
('operator',   'Manajemen Pengguna', 'Verifikasi Dokumen User', TRUE),
('supervisor', 'Manajemen Pengguna', 'Lihat Daftar User',       FALSE),
('supervisor', 'Manajemen Pengguna', 'Tambah Akun',             FALSE),
('supervisor', 'Manajemen Pengguna', 'Edit Akun',               FALSE),
('supervisor', 'Manajemen Pengguna', 'Hapus Akun',              FALSE),
('supervisor', 'Manajemen Pengguna', 'Verifikasi Dokumen User', FALSE),
-- Pengaturan Sistem
('admin',      'Pengaturan Sistem', 'Pengaturan Aplikasi',     TRUE),
('admin',      'Pengaturan Sistem', 'Pengaturan Email',        TRUE),
('admin',      'Pengaturan Sistem', 'Pengaturan Tanda Tangan', TRUE),
('admin',      'Pengaturan Sistem', 'Harga Ikan',              TRUE),
('operator',   'Pengaturan Sistem', 'Pengaturan Aplikasi',     FALSE),
('operator',   'Pengaturan Sistem', 'Pengaturan Email',        FALSE),
('operator',   'Pengaturan Sistem', 'Pengaturan Tanda Tangan', FALSE),
('operator',   'Pengaturan Sistem', 'Harga Ikan',              FALSE),
('supervisor', 'Pengaturan Sistem', 'Pengaturan Aplikasi',     FALSE),
('supervisor', 'Pengaturan Sistem', 'Pengaturan Email',        FALSE),
('supervisor', 'Pengaturan Sistem', 'Pengaturan Tanda Tangan', FALSE),
('supervisor', 'Pengaturan Sistem', 'Harga Ikan',              FALSE)
ON DUPLICATE KEY UPDATE allowed = VALUES(allowed);
