from __future__ import annotations

PROFILE_VERSION = "2026-05-11.hybrid-v2"

DEFAULT_CLASS_PROFILES: dict[str, dict[str, object]] = {
    "ekor_tikus": {
        "display_name": "Ekor Tikus",
        "summary": "Ikan dengan kepala relatif besar dan ekor sangat panjang meruncing seperti tikus.",
        "visual_traits": [
            "kepala besar",
            "ekor panjang meruncing",
            "tubuh memanjang",
            "warna cenderung abu-abu atau cokelat pucat",
        ],
        "keywords": [
            "kepala besar",
            "ekor panjang",
            "ekor meruncing",
            "ekor tikus",
            "tubuh memanjang",
            "abu abu",
            "cokelat pucat",
        ],
        "caution": "Sering tertukar dengan layur jika bagian ekor tidak terlihat jelas.",
    },
    "gelang_sadap": {
        "display_name": "Gelang Sadap",
        "summary": "Ikan laut target berwarna perak dengan badan pipih oval, tampak licin mengilap, dan bentuk tubuh relatif pendek-lebar.",
        "visual_traits": [
            "badan pipih oval",
            "warna perak mengilap",
            "bentuk relatif pendek dan lebar",
            "permukaan tubuh tampak halus",
        ],
        "keywords": [
            "perak",
            "mengilap",
            "badan pipih",
            "oval",
            "ikan pendek",
            "ikan lebar",
            "gelang sadap",
            "driftfish",
        ],
        "caution": "Kelas ini harus tetap mengikuti target gelang_sadap yang Anda inginkan; buang hasil fallback yang terlalu mirip tembang, samgeh, atau butterfish lain yang tidak sesuai.",
    },
    "keong_laut": {
        "display_name": "Keong Laut",
        "summary": "Moluska bercangkang keras dengan bentuk spiral atau kerucut yang jelas.",
        "visual_traits": [
            "ada cangkang",
            "spiral atau kerucut",
            "permukaan keras",
            "bukan tubuh ikan",
        ],
        "keywords": [
            "cangkang",
            "spiral",
            "kerucut",
            "keong",
            "siput laut",
            "permukaan keras",
        ],
        "caution": "Jika cangkang tertutup lumpur atau hanya sebagian terlihat, kelas lain non-ikan bisa mengganggu.",
    },
    "koro": {
        "display_name": "Koro",
        "summary": "Ikan memanjang dengan sirip dada berjari atau berfilamen khas threadfin.",
        "visual_traits": [
            "tubuh memanjang",
            "sirip dada berjari",
            "filamen tipis di bagian dada",
            "warna perak kekuningan",
        ],
        "keywords": [
            "sirip berjari",
            "filamen",
            "kumis dada",
            "tubuh memanjang",
            "perak",
            "kekuningan",
        ],
        "caution": "Kalau filamen sirip tidak terlihat, bisa tertukar dengan layur atau samgeh.",
    },
    "kuniran": {
        "display_name": "Kuniran",
        "summary": "Ikan dasar dengan tubuh memanjang dan kumis dagu atau barbel yang cukup jelas.",
        "visual_traits": [
            "ada kumis di dagu",
            "warna kuning kemerahan",
            "tubuh memanjang",
            "kepala agak meruncing",
        ],
        "keywords": [
            "kumis dagu",
            "barbel",
            "kuning",
            "kemerahan",
            "ikan dasar",
            "tubuh memanjang",
        ],
        "caution": "Bila barbel tertutup sudut foto, kuniran bisa bergeser ke kelas ikan memanjang lain.",
    },
    "layur": {
        "display_name": "Layur",
        "summary": "Ikan sangat panjang, pipih, dan mengilap seperti pita atau sabuk.",
        "visual_traits": [
            "tubuh sangat panjang",
            "pipih seperti pita",
            "warna perak terang",
            "kepala runcing",
        ],
        "keywords": [
            "panjang seperti pita",
            "sangat panjang",
            "pipih",
            "perak terang",
            "layur",
            "sabuk",
        ],
        "caution": "Jika hanya sebagian badan terlihat, bisa mirip ekor_tikus atau tuna kecil.",
    },
    "rajungan": {
        "display_name": "Rajungan",
        "summary": "Kepiting laut dengan karapas lebar, capit, dan kaki renang samping.",
        "visual_traits": [
            "bentuk kepiting",
            "capit jelas",
            "karapas lebar",
            "kaki renang pipih",
        ],
        "keywords": [
            "kepiting",
            "capit",
            "karapas",
            "kaki renang",
            "rajungan",
            "cangkang lebar",
        ],
        "caution": "Jika capit terpotong dari frame, model bisa hanya membaca tekstur cangkang.",
    },
    "samgeh": {
        "display_name": "Samgeh",
        "summary": "Ikan perak keabu dengan tubuh memanjang dan kepala lebih padat daripada tembang.",
        "visual_traits": [
            "warna perak keabu",
            "tubuh memanjang",
            "badan agak tebal",
            "kepala cukup besar",
        ],
        "keywords": [
            "perak",
            "keabu",
            "badan tebal",
            "tubuh memanjang",
            "kepala besar",
        ],
        "caution": "Kelas ini masih data-minim, jadi ciri tambahan sangat membantu.",
    },
    "sapu_sapu_laut": {
        "display_name": "Sapu-Sapu Laut",
        "summary": "Ikan dasar laut target dengan kepala keras bertulang, tubuh seperti berarmor, dan sirip dada atau duri samping yang sangat khas.",
        "visual_traits": [
            "kepala bertulang",
            "tubuh seperti berarmor",
            "duri atau sirip dada lebar",
            "ikan dasar laut",
            "sering merah oranye",
        ],
        "keywords": [
            "armor",
            "bertulang",
            "kepala keras",
            "duri",
            "sirip dada lebar",
            "merah oranye",
            "gurnard",
            "sapu sapu laut",
        ],
        "caution": "Kelas ini harus tetap mengarah ke sapu_sapu_laut yang Anda maksud; hapus gambar fallback yang terlalu jauh, misalnya flying gurnard yang bentuknya tidak sesuai target akhir Anda.",
    },
    "swanggi": {
        "display_name": "Swanggi",
        "summary": "Ikan bermata besar dengan warna merah atau oranye mencolok.",
        "visual_traits": [
            "mata sangat besar",
            "warna merah oranye",
            "tubuh agak tinggi",
            "mulut lebar",
        ],
        "keywords": [
            "mata besar",
            "merah",
            "oranye",
            "mulut lebar",
            "badan tinggi",
        ],
        "caution": "Kalau mata tidak tampak jelas, swanggi bisa bergeser ke samgeh atau tembang gelap.",
    },
    "tembang": {
        "display_name": "Tembang",
        "summary": "Ikan kecil ramping dengan tubuh pipih dan sisik perak khas sardinella.",
        "visual_traits": [
            "ikan kecil",
            "tubuh ramping pipih",
            "warna perak",
            "sisik jelas",
        ],
        "keywords": [
            "ikan kecil",
            "ramping",
            "pipih",
            "perak",
            "sisik",
            "tembang",
        ],
        "caution": "Bisa tertukar dengan gelang_sadap jika ukuran tubuh di foto tidak jelas.",
    },
    "tembang_hiles": {
        "display_name": "Tembang Hiles",
        "summary": "Ikan kecil ramping dengan tubuh pipih dan sisik perak khas kelompok sardinella atau clupeidae kecil.",
        "visual_traits": [
            "ikan kecil",
            "tubuh ramping pipih",
            "warna perak",
            "sisik jelas",
        ],
        "keywords": [
            "ikan kecil",
            "ramping",
            "pipih",
            "perak",
            "sisik",
            "tembang",
            "hiles",
        ],
        "caution": "Kelas ini mengikuti folder tembang_hiles; cek manual gambar yang terlalu mirip gelang_sadap atau ikan clupeidae lain yang terlalu lebar.",
    },
    "tuna": {
        "display_name": "Tuna",
        "summary": "Ikan besar berbentuk torpedo dengan badan padat dan ekor kuat.",
        "visual_traits": [
            "bentuk torpedo",
            "badan padat",
            "ekor kuat",
            "sirip punggung dan ekor tegas",
        ],
        "keywords": [
            "torpedo",
            "badan padat",
            "ekor kuat",
            "ikan besar",
            "sirip punggung",
            "tuna",
        ],
        "caution": "Jika hanya bagian tengah tubuh terlihat, tuna bisa mirip layur besar atau samgeh.",
    },
    "udang_api": {
        "display_name": "Udang Api",
        "summary": "Krustasea memanjang dengan sungut, ruas tubuh, dan ekor kipas khas udang.",
        "visual_traits": [
            "ada sungut panjang",
            "tubuh beruas",
            "ekor kipas",
            "bentuk udang",
        ],
        "keywords": [
            "udang",
            "sungut",
            "beruas",
            "ekor kipas",
            "kaki banyak",
            "antena",
        ],
        "caution": "Kalau sungut atau ekor terpotong frame, rajungan atau objek laut lain bisa ikut naik skornya.",
    },
}
